package com.mbragg.playlister.repositories;

import com.mbragg.playlister.models.entitys.Genre;
import org.springframework.data.neo4j.repository.GraphRepository;

/**
 * Concrete class is generated by Spring Data Neo4J: with CRUD boilerplate methods based on type: Genre
 *
 * @author Michael Bragg
 */
public interface GenreRepository extends GraphRepository<Genre> {

    Genre findByName(String name);

}


